# Problem Set 4B
# Name: Diogo Oliveira
# Collaborators: Diogo Oliveira

import random

class Message(object):
    def __init__(self, input_text):
        '''
        Initializes a Message object
        input_text (string): the message's text
        a Message object has one attribute:
            the message text
        '''
        
        self.input_text = input_text

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''Message('{self.get_text()}')'''

    def get_text(self):
        '''
        Used to access the message text outside of the class

        Returns: (string) the message text
        '''
        return self.input_text

    def shift_char(self, char, shift):
        char_num = ord(char)
        return chr(((char_num - 32 + shift) % 95) + 32)
    
    def apply_pad(self, pad):
        '''
        Used to calculate the ciphertext produced by applying a one time pad to the message text.
        For each character in the text at index i shift that character by
            the amount specified by pad[i]

        pad (list of ints): a list of integers used to encrypt the message text
                        len(pad) == len(the message text)

        Returns: (string) The ciphertext produced using the one time pad
        '''
        
        texto = self.input_text
        
        string = ""
        for i in range(len(pad)):
            letter = self.shift_char(texto[i], pad[i])
            string += (letter)
            
        return string

class PlaintextMessage(Message):
    def __init__(self, input_text, pad=None):
        '''
        Initializes a PlaintextMessage object.

        input_text (string): the message's text
        pad (list of ints OR None): the pad to encrypt the input_text or None if left empty
            if pad is not None then len(pad) == len(self.input_text)

        A PlaintextMessage object inherits from Message. It has three attributes:
            the message text
            the pad (list of integers, determined by pad
                or generated randomly using self.generate_pad() if pad is None)
            the ciphertext (string, input_text encrypted using the pad)
        '''
        
        self.input_text = input_text
        
        if pad is not None:
            self.pad = pad.copy()
        else:
            self.pad = self.generate_pad()

        self.ciphertext = self.apply_pad(self.pad)      
        
    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''PlaintextMessage('{self.get_text()}', {self.get_pad()})'''

    def generate_pad(self):
        '''
        Generates a one time pad which can be used to encrypt the message text.

        The pad should be generated by making a new list and for each character
            in the message chosing a random number in the range [0, 110) and
            adding that number to the list.

        Returns: (list of integers) the new one time pad
        '''
        pad = []
        
        for i in range(len(self.input_text)):
            rand = random.randint(0,109)
            pad.append(rand)
            
        return pad
    
    def get_text(self):
        return self.input_text

    def get_pad(self):
        return self.pad.copy()

    def get_ciphertext(self):
        return self.ciphertext
        

    def change_pad(self, new_pad):
        '''
        Changes the pad used to encrypt the message text and updates any other
        attributes that are determined by the pad.

        new_pad (list of ints): the new one time pad that should be associated with this message.
            len(new_pad) == len(the message text)

        Returns: nothing
        '''
        if(len(new_pad) == len(self.input_text)):
            self.pad.clear()
            self.pad = new_pad
            
        self.ciphertext = self.apply_pad(self.pad)


class EncryptedMessage(Message):
    def __init__(self, input_text):
        '''
        Initializes an EncryptedMessage object

        input_text (string): the ciphertext of the message

        an EncryptedMessage object inherits from Message. It has one attribute:
            the message text (ciphertext)
        '''
        self.input_text = input_text

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''EncryptedMessage('{self.get_text()}')'''

    def decrypt_message(self, pad):
        '''
        Decrypts the message text that was encrypted with pad as described in the writeup

        pad (list of ints): the new one time pad used to encrypt the message.
            len(pad) == len(the message text)

        Returns: (PlaintextMessage) the decrypted message (containing the pad)
        '''
        texto = self.input_text
        string = ""
        
        for i in range(len(pad)):
            letter = self.shift_char(texto[i], -pad[i])
            string += (letter)
            
        return PlaintextMessage(input_text=string, pad=pad)
    
if __name__ == '__main__':
    print("--- Testando PlaintextMessage com Pad Específico ---")
    texto_original = "Hello World!"
    
    pad_teste = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] 
    
    msg_limpa = PlaintextMessage(texto_original, pad_teste)
    
    print("Texto original:", msg_limpa.get_text())
    print("Pad utilizado:", msg_limpa.get_pad())
    print("Texto Cifrado:", msg_limpa.get_ciphertext())
    
    print("\n--- Testando EncryptedMessage e Descriptografia ---")

    msg_cifrada = EncryptedMessage(msg_limpa.get_ciphertext())
    
    print("Mensagem Recebida (Cifrada):", msg_cifrada.get_text())
    
    msg_descriptografada = msg_cifrada.decrypt_message(pad_teste)
    
    print("Mensagem Descriptografada:", msg_descriptografada.get_text())
    
    print("\n--- Testando PlaintextMessage com Pad Aleatório ---")
    msg_aleatoria = PlaintextMessage("Python MIT PSet")
    print("Texto original:           ", msg_aleatoria.get_text())
    
    pad_aleatorio = msg_aleatoria.get_pad()
    
    print("Pad gerado aleatoriamente:", pad_aleatorio)
    print("Texto Cifrado (Aleatório):", msg_aleatoria.get_ciphertext())
    
    msg_aleatoria_cifrada = EncryptedMessage(msg_aleatoria.get_ciphertext())
    
    msg_aleatoria_decrifrada = msg_aleatoria_cifrada.decrypt_message(pad=pad_aleatorio)
    print("Mensagem Descriptografada:", msg_aleatoria_decrifrada.get_text())